version: '3.8'
services:
  neo4j:
    image: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./data:/data
    environment:
      - NEO4J_AUTH=neo4j/11111111
  flask:
    build: .
    ports:
      - "5000:5000"
